---
# @author Anthony Loukinas <anthony.loukinas@redhat.com>

- hosts: localhost
  gather_facts: no
  tasks:

    # Setup AWX
    - include_role:
        name: awx_setup
        apply:
          tags: build

  module_defaults:
    tower_project:
      tower_host: "{{ tower_host }}"
      tower_username: "admin"
      tower_password: "{{ admin_password }}"
      validate_certs: no