---
# @author Anthony Loukinas <anthony.loukinas@redhat.com>

- hosts: localhost
  gather_facts: no
  tasks:

    # Setup AWX
    - include_role:
        name: awx_teardown

  module_defaults:
    tower_project:
      tower_host: "{{ tower_host }}"
      tower_username: "{{ tower_username }}"
      tower_password: "{{ tower_password }}"
      validate_certs: no