---
# @author Anthony Loukinas <anthony.loukinas@redhat.com>

- name: Shutdown docker containers
  docker_container:
    name: "{{ item }}"
    state: absent
  loop:
    - "{{ tower_env }}_awx_web"
    - "{{ tower_env }}_awx_task"
    - "{{ tower_env }}_rabbitmq"
    - "{{ tower_env }}_memcached"
    - "{{ tower_env }}_postgres"

- name: Remove docker network
  docker_network:
    name: "{{ tower_env }}_tower_net"
    state: absent